<a href="https://colab.research.google.com/github/bharathkumaarr/pytorch-tut/blob/master/tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [5]:
my_tensor = torch.arange(10)
my_tensor #tensor of 10 elements 0 to 9

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**TENSOR OPERATIONS**

Reshape & View

In [14]:
tensor1 = my_tensor.reshape(2,5)
tensor1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
#reshape if we don't knwo the number of elements in the tensor
tensor2 = torch.arange(10)
tensor2=tensor2.reshape(2,-1)
tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
tensor2 =tensor2.reshape(-1,5)
tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

VIEW

In [23]:
tensor3=torch.arange(10)
tensor3 = tensor3.view(2,5)
tensor3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [25]:
#updates in reshape and view

In [30]:
tensor5 = torch.arange(10)
tensor6=tensor5.reshape(2,5)
tensor6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [31]:
tensor5[4] = 54321
tensor5

tensor([    0,     1,     2,     3, 54321,     5,     6,     7,     8,     9])

In [32]:
tensor6

tensor([[    0,     1,     2,     3, 54321],
        [    5,     6,     7,     8,     9]])

****SLICES****

In [34]:
tensor7 = torch.arange(10)
tensor7[5]

tensor(5)

In [35]:
tensor8=tensor7.reshape(5,2)
tensor8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [36]:
tensor8[:,1]

tensor([1, 3, 5, 7, 9])

In [37]:
tensor8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])