<a href="https://colab.research.google.com/github/bharathkumaarr/pytorch-tut/blob/master/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR** is just another array, or a numpy array. just like lists but more powerful. tensors are used in deep learning.

default datatype is float32



In [1]:
import torch
import numpy as np

**LISTS**

In [4]:
my_list = [1,2,3,4]
my_list2 = [[1,2,3], [3,3,4]] #multi-dimensional

print(my_list)
print(my_list2)

[1, 2, 3, 4]
[[1, 2, 3], [3, 3, 4]]


**NUMPY ARRAYS**

In [8]:
np1 = np.random.rand(3,4)
np1

array([[0.30422007, 0.99564639, 0.56636487, 0.1157195 ],
       [0.70942354, 0.60448068, 0.11368609, 0.86444003],
       [0.10001585, 0.54362769, 0.85542166, 0.87842345]])

In [9]:
np1.dtype

dtype('float64')

In [12]:
tensor_2d = torch.randn(3,4)
print(tensor_2d)

tensor([[-0.8601,  0.1651,  0.9087,  0.7101],
        [ 0.4685,  1.6111, -1.2078, -1.8143],
        [ 0.9351, -0.3987,  1.8462,  0.2739]])


In [13]:
tensor_2d.dtype

torch.float32

In [14]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[ 2.1520,  2.2312, -0.5475,  1.1302],
         [-0.8485,  0.4062, -0.3727, -0.3444],
         [ 0.6571, -1.4817, -2.2921,  0.3877]],

        [[ 0.7258,  0.2786,  0.3474,  0.0911],
         [-0.5667,  1.7847, -0.0674, -0.7699],
         [-0.9189,  0.3277, -0.2226, -2.0172]]])

In [15]:
#create tensor out of numpy arr
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3042, 0.9956, 0.5664, 0.1157],
        [0.7094, 0.6045, 0.1137, 0.8644],
        [0.1000, 0.5436, 0.8554, 0.8784]], dtype=torch.float64)

In [16]:
my_tensor.dtype

torch.float64